### ISSUE TITLE
Assignment 3-Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 41bit23** [vtcbca/basic-programming-50bit23#2]
What is Fibonacci Sequence Generator?

**Comment by 50bit23** [comment]
The Fibonacci sequence is a set of integers (the Fibonacci numbers) that starts with a zero, followed by a one, then by another one, and then by a series of steadily increasing numbers.

**Comment by 41bit23** [comment]
What is the formula for generating the Fibonacci sequence?

**Comment by 50bit23** [comment]
The formula for generating the Fibonacci sequence is  (Fn=Fn-1+Fn-2)

**Comment by 41bit23** [comment]
What is Fibonacci number in programming?

**Comment by 50bit23** [comment]
In programming, the Fibonacci number is a number in the Fibonacci sequence, which is a series of numbers where each number is the sum of the two numbers that come before it.

**Comment by 41bit23** [comment]
Why is Fibonacci so special?

**Comment by 50bit23** [comment]
a ration that describes when a line is divided into two parts and the longer part (a) divided by the smaller part (b) is equal to the sum of (a) + (b) divided by (a), which both equal 1.618.

**Comment by 41bit23** [comment]
It's really helpful for me Thank you so much
