### ISSUE TITLE
Assignment 6-Pattern of *

### ISSUE THREAD

**Issue by 45bit23** [vtcbca/basic-programming-50bit23#3]
What do you mean by Pattern ?

**Comment by 50bit23** [comment]
In Python, a pattern is a design that is made up of symbols, numbers, or characters that repeat a certain number of times. Pattern programs in Python are a type of exercise that use loops to print these patterns on the console.

**Comment by 45bit23** [comment]
can you explain it through example?

**Comment by 50bit23** [comment]
def pattern_one_line(n):
    for i in range(1, n + 1):
        print(" ".join("*" * i))
This is the simple example for beginner.

**Comment by 45bit23** [comment]
What is the pattern method?

**Comment by 50bit23** [comment]
It is used to get the regular expression which is compiled to create this pattern.

**Comment by 45bit23** [comment]
What is a logic pattern?

**Comment by 50bit23** [comment]
Logical patterns match events that arrive in temporal order and correlate them with logical relationships such as and , or and not .

**Comment by 45bit23** [comment]
I get it. Thank you very much
