### ISSUE TITLE
Assignment-1 Factorial 

### ISSUE THREAD

**Issue by 47bit23** [vtcbca/basic-programming-50bit23#4]
What do you mean by factor ?

**Comment by 50bit23** [comment]
A number or algebraic expression that divides another number or expression evenly—i.e., with no remainder. For example, 3 and 6 are factors of 12 because 12 ÷ 3 = 4 exactly and 12 ÷ 6 = 2 exactly. The other factors of 12 are 1, 2, 4, and 12.

**Comment by 47bit23** [comment]
Can you give a brief example ?

**Comment by 47bit23** [comment]
The process of finding the factors for a given number is better understood by making suitable arrangements. For example, to find the factors of 2, we have to arrange two objects differently. These arrangements are useful for writing the factors of a number.

**Comment by 47bit23** [comment]
How can you implement a factorial calculator using recursion in Python?

**Comment by 47bit23** [comment]
To implement a factorial calculator using recursion in Python, you need to define a function that calls itself to compute the factorial of a number. The base case will be when the number is 0 or 1, since the factorial of both 0 and 1 is 1. For any other number, the function will multiply the number by the factorial of the previous number.

**Comment by 47bit23** [comment]
OH now i got the concept

**Comment by 50bit23** [comment]
The process of finding the factors for a given number is better understood by making suitable arrangements. For example, to find the factors of 2, we have to arrange two objects differently. These arrangements are useful for writing the factors of a number.

**Comment by 47bit23** [comment]
How can you implement a factorial calculator using recursion in Python?

**Comment by 47bit23** [comment]
To implement a factorial calculator using recursion in Python, you need to define a function that calls itself to compute the factorial of a number. The base case will be when the number is 0 or 1, since the factorial of both 0 and 1 is 1. For any other number, the function will multiply the number by the factorial of the previous number.

**Comment by 50bit23** [comment]
To implement a factorial calculator using recursion in Python, you need to define a function that calls itself to compute the factorial of a number. The base case will be when the number is 0 or 1, since the factorial of both 0 and 1 is 1. For any other number, the function will multiply the number by the factorial of the previous number.

**Comment by 50bit23** [comment]
OH !! Now i got the concept .

**Comment by 47bit23** [comment]
OH! Now i got the concept.

**Comment by 50bit23** [comment]
YEAHH that's damn easy .

**Comment by 47bit23** [comment]
Thanks !!!
