### ISSUE TITLE
Assignment-7  : Traiangle Pattern of Number

### ISSUE THREAD

**Issue by 51bit23** [vtcbca/basic-programming-50bit23#5]
What is a triangle pattern of numbers?

**Comment by 50bit23** [comment]
It’s a pattern where numbers are arranged in rows to form a triangle-like structure.

**Comment by 51bit23** [comment]
How do you generate a triangle pattern up to a given number of lines?

**Comment by 50bit23** [comment]
Use nested loops: an outer loop for rows and an inner loop for numbers in each row

**Comment by 51bit23** [comment]
How do you take input for the number of lines in the pattern?

**Comment by 50bit23** [comment]
Use the input() function to ask the user for the number of rows:

`n = int(input("Enter the number of rows: "))`

**Comment by 51bit23** [comment]
ow do you align the numbers properly in a triangle shape?

**Comment by 50bit23** [comment]
Use spaces before numbers in each row:

`print(" " * (n - i), end="")`

**Comment by 51bit23** [comment]
What is the role of the inner loop in this program?

**Comment by 50bit23** [comment]
The inner loop generates the numbers for each row.
